name: Deploy Docusaurus site to GitHub Pages

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發部署（可根據情況更改）

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # 確保 Node.js 版本符合 Docusaurus 專案需求

      - name: Install dependencies
        run: npm install

      - name: Build Docusaurus site
        run: npm run build

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub 自動生成的 token
        run: |
          npm install -g gh-pages  # 安裝 gh-pages，用於部署
          USE_SSH=true GIT_USER=$(git config user.name) GIT_EMAIL=$(git config user.email) npx docusaurus deploy
